name: Maven Package upon a push

on:
  release:
    types: [published]
  pull_request:
    types: [opened]
    branches:
      - '!release-branch'
      - release-1*
      - 1.*
      - develop
      - MOSIP*
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - release-1*
      - master
      - 1.*
      - develop

jobs:
  build-dockers:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: './'
            SERVICE_NAME: 'mock-smtp'
      fail-fast: false
    uses: mosip/kattu/.github/workflows/docker-build.yml@master
    name: ${{ matrix.SERVICE_NAME }}
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}